[package]
name = "didwebs-affinidi-check-patched"
version = "0.1.0"
edition = "2024"

[dependencies]
affinidi-did-webs = { git = "ssh://git@github.com/bakobo/affinidi-tdk-rs.git", rev = "f9d07b4feaaa25fab4d74c435b89f83f5011e7b6" }
serde_json = "1"

[dev-dependencies]
tempfile = "3"

[profile.dev]
debug = 0
